// Examples/Widgets/RSS/lit-element/src/components/App.ts
/**
 * Copyright (c) Cisco Systems, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { agentxJsApi } from "@agentx/agentx-js-api";
import { html, LitElement, customElement, internalProperty, property, PropertyValues } from "lit-element";
import styles from "./App.scss";
import { logger } from "./sdk";
import { Service } from "@agentx/agentx-services-types";
import { Notifications } from "@uuip/unified-ui-platform-sdk";
@customElement("my-custom-component")
export default class MyCustomComponent extends LitElement {
  @property({type: String}) rssFeedAddress = "https://www.who.int/feeds/entity/csr/don/en/rss.xml"
  /**
   * Replace this with the logic to obtain interaction ID you need
   * through agentxJsApi.actions sub-module or through external props
   */
  @internalProperty() sampleInteractionId: Service.Aqm.Contact.Interaction["interactionId"] =
    "58f76ca3-409f-11eb-8606-f1b296a9b969";
  @internalProperty() agentId = "7d12d9ea-e8e0-41ee-81bf-c11a685b64ed";
  @internalProperty() buddyAgents: Service.Aqm.Contact.BuddyAgentsSuccess | null = null;
  @internalProperty() vTeam: Service.Aqm.Contact.VTeamSuccess | null = null;
  @internalProperty() contacts: Service.Aqm.Contact.Interaction["interactionId"][] = [];
  @internalProperty() acceptedContacts: Service.Aqm.Contact.Interaction["interactionId"][] = [];

  @internalProperty() rssFeedItems?: NodeListOf<Element>;
  @internalProperty() totalPage: number = 1;
  @internalProperty() hasPreviousPage: boolean = true;
  @internalProperty() hasNextPage: boolean = true;
  @internalProperty() currentPage: number = 1;

  static get styles() {
    return styles;
  }

  firstUpdated(changedProperties: PropertyValues){
    super.firstUpdated(changedProperties)
    this.getFeed();
  }

  connectedCallback() {
    super.connectedCallback();
    this.init();
    this.getCurrentInteractionId();
    this.subscribeAgentContactDataEvents()
    this.subscribeDialerEvents();
    this.subscribeScreenpopEvent();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    agentxJsApi.agentContact.removeAllEventListeners();
    agentxJsApi.dialer.removeAllEventListeners();
    agentxJsApi.screenpop.removeAllEventListeners()
  }

  async init() {
    await agentxJsApi.config.init();
  }

  subscribeScreenpopEvent() {
    agentxJsApi.screenpop.addEventListener("eScreenPop", (msg: Service.Aqm.Contact.AgentContact) => logger.info(msg));
  }

  subscribeDialerEvents() {
    agentxJsApi.dialer.addEventListener("eOutdialFailed", (msg: Service.Aqm.Contact.AgentContact) => logger.info(msg));
  }

  subscribeAgentContactDataEvents() {
    agentxJsApi.agentContact.addEventListener("eAgentContact", (msg: Service.Aqm.Contact.AgentContact) =>
      logger.info("AgentContact eAgentContact: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentContactAssigned",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info("AgentContact eAgentContactAssigned: ", msg);
        this.acceptedContacts.push(msg.data.interactionId);
        logger.info(this.acceptedContacts);
      }
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentContactEnded",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info("AgentContact eAgentContactEnded: ", msg);
        const idx = this.acceptedContacts.indexOf(msg.data.interactionId);
        if (idx != -1) {
          this.acceptedContacts = this.acceptedContacts.slice(idx, 1);
          logger.info(this.acceptedContacts);
        }
      }
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentContactWrappedUp",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentContactWrappedUp: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentOfferContact",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info("AgentContact eAgentOfferContact: ", msg);
        // AUX Sandbox Contact
        this.contacts.push(msg.data.interactionId);
        logger.info(this.contacts);
      }
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentOfferContactRona",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info("AgentContact eAgentOfferContactRona: ", msg);
        // AUX Sandbox Contact
        const idx = this.contacts.indexOf(msg.data.interactionId);
        if (idx != -1) {
          this.contacts = this.contacts.slice(idx, 1);
          logger.info(this.contacts);
        }
      }
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentOfferConsult",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentOfferConsult: ", msg)
    );
    agentxJsApi.agentContact.addEventListener("eAgentWrapup", (msg: Service.Aqm.Contact.AgentContact) =>
      logger.info("AgentContact eAgentWrapup: ", msg)
    );
    agentxJsApi.agentContact.addEventListener("eAgentContactHeld", (msg: Service.Aqm.Contact.AgentContact) =>
      logger.info("AgentContact eAgentContactHeld: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentContactUnHeld",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentContactUnHeld: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eCallRecordingStarted",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eCallRecordingStarted: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentConsultCreated",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentConsultCreated: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentConsultConferenced",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentConsultConferenced: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentConsultEnded",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentConsultEnded: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentCtqCancelled",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentCtqCancelled: ", msg)
    );
    agentxJsApi.agentContact.addEventListener("eAgentConsulting", (msg: any) =>
      logger.info("AgentContact eAgentConsulting: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentConsultFailed",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentConsultFailed: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentConsultEndFailed",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentConsultEndFailed: ", msg)
    );
    agentxJsApi.agentContact.addEventListener("eAgentCtqFailed", (msg: any) =>
      logger.info("AgentContact eAgentCtqFailed: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentCtqCancelFailed",
      (msg: Service.Aqm.Contact.AgentContact) => logger.info("AgentContact eAgentCtqCancelFailed: ", msg)
    );
    agentxJsApi.agentContact.addEventListener(
      "eAgentConsultConferenceEndFailed",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultConferenceEndFailed: ", msg)
    );
  }

  getCurrentInteractionId() {
    let path = window.location.pathname;
    if (path.indexOf("task") >= 0 && path.replace("task/", "").length > 0) {
      this.sampleInteractionId = path.replace("/task/", "");
      logger.info("Current interactionID: ", this.sampleInteractionId);
    }
  }

  async changeState(s: "Available" | "Idle") {
    const agentState = await agentxJsApi.agentStateInfo.stateChange({
      state: s,
      auxCodeIdArray: "0",
    });
    logger.info("State Changed", agentState);
  }

  async getAgentAddressBooks() {
    const books = await agentxJsApi.agentStateInfo.fetchAddressBooks();
    logger.info("Address books: ", books);
  }

  async getAgentInfo() {
    const latestData = agentxJsApi.agentStateInfo.latestData;
    logger.info("AgentStateInfo latestData: ", latestData);
  }

  getClientLocale() {
    logger.info("Client locale: ", agentxJsApi.config.clientLocale);
  }

  async getToken() {
    const token = await agentxJsApi.actions.getToken();
    logger.info(token);
  }

  async getIdleCodes() {
    const idle = await agentxJsApi.actions.getIdleCodes();
    logger.info(idle);
  }

  async getwrapupCodes() {
    const wrapup = await agentxJsApi.actions.getWrapUpCodes();
    logger.info(wrapup);
  }

  // async fireNotification() {
  //   const raw: Notifications.ItemMeta.Raw = {
  //     data: {
  //       type: Notifications.ItemMeta.Type.Info,
  //       mode: Notifications.ItemMeta.Mode.AutoDismiss,
  //       title: "Info - Acknowledge",
  //       data: "Lorem Ipsum Dolor"
  //     }
  //   };
  //   const [ status, reason, mode ]: [ Notifications.ItemMeta.Status, Notifications.ItemMeta.StatusChangeEventReason, Notifications.ItemMeta.Mode ] = await agentxJsApi.actions.fireGeneralAutoDismissNotification(raw as Notifications.ItemMeta.Raw & { data: { mode: Notifications.ItemMeta.Mode.AutoDismiss; }; })
  //   logger.info(status, reason, mode);
  // }

  async getBuddyAgents() {
    const buddyAgentPayload = {
      agentProfileId: "AXCLfZhH9S1oTdqE1OFw",
      channelName: "chat",
      state: "Available",
    };

    this.buddyAgents = await agentxJsApi.agentContact.buddyAgents({
      data: buddyAgentPayload,
    });
    logger.info(this.buddyAgents);
  }

  async getVTeamList() {
    const vTeamPayload = {
      agentProfileId: "AXCLfZhH9S1oTdqE1OFw",
      agentSessionId: "5a84d32c-691b-4500-b163-d6cdba2a3163",
      channelType: "chat",
      type: "inboundqueue",
    };

    this.vTeam = await agentxJsApi.agentContact.vteamList({
      data: vTeamPayload,
    });
    logger.info(this.vTeam, this.vTeam!.data.data.vteamList);
  }

  async acceptInteraction(interactionId: string) {
    let acceptInteraction = await agentxJsApi.agentContact.accept({
      interactionId: interactionId,
    });
    logger.info(acceptInteraction);
  }

  async endInteraction() {
    let endedInteraction = await agentxJsApi.agentContact.end({
      interactionId: this.sampleInteractionId,
    });
    logger.info(endedInteraction);
  }

  async wrapUpInteraction() {
    let wrappedUpInteraction = await agentxJsApi.agentContact.wrapup({
      interactionId: this.sampleInteractionId,
      data: {
        wrapUpReason: "Example reason here",
        auxCodeId: "0",
        isAutoWrapup: "false",
      },
    });
    logger.info(wrappedUpInteraction);
  }

  async consultWithAgent() {
    let consult = await agentxJsApi.agentContact.consult({
      interactionId: this.sampleInteractionId,
      data: {
        agentId: this.agentId,
        destAgentId: this.buddyAgents?.data.agentList[0].agentId,
        mediaType: "chat",
      },
      url: "consult",
    });
    logger.info(consult);
  }

  async consultConferenceWithAgent() {
    let consult = await agentxJsApi.agentContact.consultConference({
      interactionId: this.sampleInteractionId,
      data: {
        agentId: this.agentId,
        destAgentId: this.buddyAgents?.data.agentList[0].agentId,
        mediaType: "chat",
      },
    });
    logger.info(consult);
  }

  async endConferenceWithAgent() {
    let consult = await agentxJsApi.agentContact.consultEnd({
      interactionId: this.sampleInteractionId,
      isConsult: false,
    });
    logger.info(consult);
  }

  async endConsultConferenceWithAgent() {
    let consult = await agentxJsApi.agentContact.consultEnd({
      interactionId: this.sampleInteractionId,
      isConsult: true,
    });
    logger.info(consult);
  }

  async consultTransferToAgent() {
    let consult = await agentxJsApi.agentContact.consultTransfer({
      interactionId: this.sampleInteractionId,
      data: {
        agentId: this.agentId,
        destAgentId: this.buddyAgents?.data.agentList[0].agentId,
        mediaType: "chat",
        mediaResourceId: "b102ed10-fac2-4f8e-bece-1c2da6ba6dd8",
      },
    });
    logger.info(consult);
  }

  async vTeamTransfer() {
    let consult = await agentxJsApi.agentContact.vteamTransfer({
      interactionId: this.sampleInteractionId,
      data: {
        vteamId: this.vTeam?.data.data.vteamList[0].analyzerId,
        vteamType: this.vTeam?.data.data.vteamList[0].type,
      },
    });
    logger.info(consult);
  }

  // objective:
  // get feed data from address
  // update total pages when fetch runs
  async getFeed() {
    await fetch(this.rssFeedAddress)
      .then(response => response.text())
      .then(str => new window.DOMParser().parseFromString(str, "text/xml"))
      .then(data => {
        this.rssFeedItems = data.querySelectorAll("item");
        this.totalPage = this.rssFeedItems.length;
      })
  }
  // parse Items into <md-link> tags that have the <title> for text and <link> for hyperlink.
  // set timer to animate slide right to left, increment current page prop
  // 


  private computeFirst() {
    if (this.currentPage >= 1) {
      this.currentPage = 1;
    }
  }

  private computeNext(page: number) {
    if (page <= this.totalPage && page !== this.currentPage) {
      this.currentPage += 1;
    }
  }

  getPageArrows() {
    return html`
    <md-button hasRemoveStyle class="md-pagination-nav" aria-label="First Page" ?disabled=${!this.hasPreviousPage}
      aria-disabled=${this.hasPreviousPage} @click=${this.computeFirst} part="pagination-first">
      <md-icon name="icon-arrow-left_16"></md-icon>
    </md-button>
    <md-button hasRemoveStyle class="md-pagination-nav" aria-label="Previous Page" ?disabled=${!this.hasNextPage}
      aria-disabled=${this.hasNextPage} @click=${() => this.computeNext(this.currentPage + 1)}
      part="pagination-next"
      >
      <md-icon name="icon-arrow-right_16"></md-icon>
    </md-button>
  `
  }

  render() {
    return html`
      <div class="container">
        <md-badge color="blue">
          <md-icon name="icon-rss-circle_24" color="blue" size="12"></md-icon>
          Current RSS Feed Item
          ${this.getPageArrows()}
        </md-badge>
      </div>
    `;
  }
}

// react/src/direflow-component/App.tsx
import React, { FC, useEffect, useRef, useState } from "react";
import { Styled } from "direflow-component";
import styles from "./App.css";
import { logger } from "./sdk";
import { Service } from "@wxcc-desktop/sdk-types";
import { Notifications } from "@uuip/unified-ui-platform-sdk";
import { Desktop } from "@wxcc-desktop/sdk";
interface IProps {
  agentId: string;
  darkTheme: boolean;
}

const App: FC<IProps> = (props) => {
  /**
   * These values will be replaced with STORE values through Data provider
   * in JSON layout configuration file
   * Data provider documentation:
   * https://apim-dev-portal.appstaging.ciscoccservice.com/documentation/guides/desktop#data-provider%E2%80%94widget-properties-and-attributes
   */

  const [agentId, setAgentId] = useState(
    "7d12d9ea-e8e0-41ee-81bf-c11a685b64ed"
  );

  const [agentSessionId, setSessionId] = useState("");
  const [agentProfileId, setProfileId] = useState("");
  const [contacts, setContacts] = useState([] as string[]);
  const [acceptedContacts, setAcceptedContacts] = useState([] as string[]);
  const [sampleInteractionId, setSampleIntId] = useState(
    "58f76ca3-409f-11eb-8606-f1b296a9b969"
  );

  const [titleFor, setTitleFor] = useState("");
  const newInteractionId = useRef<any>(null);

  const [buddyAgents, setBuddyAgents] = useState(
    null as Service.Aqm.Contact.BuddyAgentsSuccess | null
  );
  const [vTeam, setVTeam] = useState(
    null as Service.Aqm.Contact.VTeamSuccess | null
  );
  const [assignedContacts, setAssignedContacts] = useState(
    [] as {
      interaction: Service.Aqm.Contact.Interaction;
    }[]
  );

  useEffect(() => {
    init();

    getCurrentInteractionId();
    subscribeAgentContactDataEvents();
    subscribeDialerEvents();
    subscribeScreenpopEvent();

    setAgentId(props.agentId);

    return () => {
      Desktop.agentContact.removeAllEventListeners();
      Desktop.dialer.removeAllEventListeners();
      Desktop.screenpop.removeAllEventListeners();
    };
  }, []);

  useEffect(() => {}, [props.agentId, props.darkTheme]);

  async function init() {
    await Desktop.config.init();
  }

  const subscribeScreenpopEvent = () => {
    Desktop.screenpop.addEventListener("eScreenPop", (msg) => logger.info(msg));
  };

  const subscribeDialerEvents = () => {
    Desktop.dialer.addEventListener("eOutdialFailed", (msg) =>
      logger.info(msg)
    );
  };

  const subscribeAgentContactDataEvents = () => {
    Desktop.agentContact.addEventListener("eAgentContact", (msg) =>
      logger.info("AgentContact eAgentContact: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentContactAssigned",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info("AgentContact eAgentContactAssigned: ", msg);
        setAcceptedContacts([...acceptedContacts, msg.data.interactionId]);
        logger.info(acceptedContacts);
      }
    );
    Desktop.agentContact.addEventListener(
      "eAgentContactEnded",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info("AgentContact eAgentContactEnded: ", msg);
        const idx = acceptedContacts.indexOf(msg.data.interactionId);
        if (idx !== -1) {
          setAcceptedContacts(acceptedContacts.slice(idx, 1));
          logger.info(acceptedContacts);
        }
      }
    );
    Desktop.agentContact.addEventListener(
      "eAgentContactWrappedUp",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentContactWrappedUp: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentOfferContact",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info(
          "AgentContact eAgentOfferContact: ",
          msg.data.interactionId
        );
        // AUX Sandbox Contact
        setContacts([...contacts, msg.data.interactionId]);
        logger.info("AgentContact eAgentOfferContact: ", contacts);
      }
    );
    Desktop.agentContact.addEventListener(
      "eAgentOfferContactRona",
      (msg: Service.Aqm.Contact.AgentContact) => {
        logger.info(
          "AgentContact eAgentOfferContactRona: ",
          msg.data.interactionId
        );
        // AUX Sandbox Contact
        const idx = contacts.indexOf(msg.data.interactionId);
        if (idx !== -1) {
          setContacts([
            ...contacts.filter(
              (interactionId) => interactionId !== msg.data.interactionId
            ),
          ]);
          logger.info("AgentContact eAgentOfferContactRona: ", contacts);
        }
      }
    );
    Desktop.agentContact.addEventListener(
      "eAgentOfferConsult",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentOfferConsult: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentWrapup",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentWrapup: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentContactHeld",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentContactHeld: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentContactUnHeld",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentContactUnHeld: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eCallRecordingStarted",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eCallRecordingStarted: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentConsultCreated",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultCreated: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentConsultConferenced",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultConferenced: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentConsultEnded",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultEnded: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentCtqCancelled",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentCtqCancelled: ", msg)
    );
    Desktop.agentContact.addEventListener("eAgentConsulting", (msg: any) =>
      logger.info("AgentContact eAgentConsulting: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentConsultFailed",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultFailed: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentConsultEndFailed",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultEndFailed: ", msg)
    );
    Desktop.agentContact.addEventListener("eAgentCtqFailed", (msg: any) =>
      logger.info("AgentContact eAgentCtqFailed: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentCtqCancelFailed",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentCtqCancelFailed: ", msg)
    );
    Desktop.agentContact.addEventListener(
      "eAgentConsultConferenceEndFailed",
      (msg: Service.Aqm.Contact.AgentContact) =>
        logger.info("AgentContact eAgentConsultConferenceEndFailed: ", msg)
    );
  };

  const getCurrentInteractionId = () => {
    let path = window.location.pathname;
    if (path.indexOf("task") >= 0 && path.replace("task/", "").length > 0) {
      setSampleIntId(path.replace("/task/", ""));
      logger.info("Current interactionID: ", sampleInteractionId);
    }
  };

  const getAgentInfo = () => {
    const latestData = Desktop.agentStateInfo.latestData;
    logger.info("AgentStateInfo latestData: ", latestData);
    if (latestData.agentProfileID) {
      setProfileId(latestData.agentProfileID);
    }

    if (latestData.subStatus) {
      setSessionId(latestData.subStatus);
    }
  };

  const getClientLocale = () => {
    logger.info("Client locale: ", Desktop.config.clientLocale);
  };

  async function changeState(s: "Available" | "Idle") {
    const agentState = await Desktop.agentStateInfo.stateChange({
      state: s,
      auxCodeIdArray: "0",
    });
    logger.info("State Changed", agentState);
  }

  async function getAgentAddressBooks() {
    const books = await Desktop.agentStateInfo.fetchAddressBooks();
    logger.info("Address books: ", books);
  }

  async function getBuddyAgents() {
    const buddyAgentPayload = {
      agentProfileId: agentProfileId,
      channelName: "chat",
      state: "Available",
    };

    const myBuddyAgents =
      (await Desktop.agentContact.buddyAgents({
        data: buddyAgentPayload,
      })) || null;

    setBuddyAgents(myBuddyAgents);
    logger.info(buddyAgents);
  }

  async function getVTeamList() {
    const vTeamPayload = {
      agentProfileId: agentProfileId,
      agentSessionId: agentSessionId,
      channelType: "chat",
      type: "inboundqueue",
    };

    const myvTeam =
      (await Desktop.agentContact.vteamList({
        data: vTeamPayload,
      })) || null;

    setVTeam(myvTeam);
    logger.info(vTeam, vTeam!.data.data.vteamList);
  }

  async function acceptInteraction(interactionId: string) {
    const acceptInteraction = await Desktop.agentContact.accept({
      interactionId: interactionId,
    });
    logger.info(acceptInteraction);

  }

  async function endInteraction() {
    const endedInteraction = await Desktop.agentContact.end({
      interactionId: sampleInteractionId,
    });
    logger.info(endedInteraction);
  }

  async function wrapUpInteraction() {
    const wrappedUpInteraction = await Desktop.agentContact.wrapup({
      interactionId: sampleInteractionId,
      data: {
        wrapUpReason: "Example reason here",
        auxCodeId: "0",
        isAutoWrapup: "false",
      },
    });
    logger.info(wrappedUpInteraction);
  }

  async function consultWithAgent() {
    const consult = await Desktop.agentContact.consult({
      interactionId: sampleInteractionId,
      data: {
        agentId: agentId,
        destAgentId: buddyAgents?.data.agentList[0].agentId,
        mediaType: "chat",
      },
      url: "consult",
    });
    logger.info(consult);
  }

  async function endConferenceWithAgent() {
    const consult = await Desktop.agentContact.consultEnd({
      interactionId: sampleInteractionId,
      isConsult: false,
    });
    logger.info(consult);
  }

  async function consultConferenceWithAgent() {
    const consult = await Desktop.agentContact.consultConference({
      interactionId: sampleInteractionId,
      data: {
        agentId: agentId,
        destAgentId: buddyAgents?.data.agentList[0].agentId,
        mediaType: "chat",
      },
    });
    logger.info(consult);
  }

  async function endConsultConferenceWithAgent() {
    const consult = await Desktop.agentContact.consultEnd({
      interactionId: sampleInteractionId,
      isConsult: true,
    });
    logger.info(consult);
  }

  async function consultTransferToAgent() {
    if (buddyAgents?.data.agentList[0].agentId) {
      const consult = await Desktop.agentContact.consultTransfer({
        interactionId: sampleInteractionId,
        data: {
          agentId: agentId,
          destAgentId: buddyAgents?.data.agentList[0].agentId,
          mediaType: "chat",
          mediaResourceId: "b102ed10-fac2-4f8e-bece-1c2da6ba6dd8",
        },
      });
      logger.info(consult);
    } else {
      logger.info("consultTransferToAgent(): agentId is not defined");
    }
  }

  async function vTeamTransfer() {
    if (
      vTeam?.data.data.vteamList[0].analyzerId &&
      vTeam?.data.data.vteamList[0].type
    ) {
      const consult = await Desktop.agentContact.vteamTransfer({
        interactionId: sampleInteractionId,
        data: {
          vteamId: vTeam?.data.data.vteamList[0].analyzerId,
          vteamType: vTeam?.data.data.vteamList[0].type,
        },
      });
      logger.info(consult);
    } else {
      if (!vTeam?.data.data.vteamList[0].analyzerId) {
        logger.info("vTeamTransfer(): analyzerId is not defined");
      }
      if (!vTeam?.data.data.vteamList[0].type) {
        logger.info("vTeamTransfer(): type is not defined");
      }
    }
  }

  async function getToken() {
    const token = await Desktop.actions.getToken();
    logger.info(token);
  }

  async function getIdleCodes() {
    const idle = await Desktop.actions.getIdleCodes();
    logger.info(idle);
  }

  async function getwrapupCodes() {
    const wrapup = await Desktop.actions.getWrapUpCodes();
    logger.info(wrapup);
  }

  async function fireNotification() {
    const raw: Notifications.ItemMeta.Raw = {
      data: {
        type: Notifications.ItemMeta.Type.Info,
        mode: Notifications.ItemMeta.Mode.AutoDismiss,
        title: "Info - Acknowledge",
        data: "Lorem Ipsum Dolor",
      },
    };
    const res = await Desktop.actions.fireGeneralAutoDismissNotification(
      raw as Notifications.ItemMeta.Raw & {
        data: { mode: Notifications.ItemMeta.Mode.AutoDismiss };
      }
    );
    if (res) {
      const [status, reason, mode] = res;
      logger.info(status, reason, mode);
    }
  }

  async function getTaskMap() {
    const taskMap = await Desktop.actions.getTaskMap();
    console.log(taskMap);
    const myAssignedContacts = Array.from(taskMap?.values() || []);
    setAssignedContacts(myAssignedContacts);
    console.log(assignedContacts[0]);
  }


  async function updateCADVariable() {
    try {
      const contactPayload = {
        attributes:{
          diallerName: "agent-name",
          diallerPhoneNumber: "+1 010 010 010"
        }
      };
      await Desktop.dialer.updateCadVariables({interactionId:"123", data: contactPayload});
    } catch(e) {
      // Handle Exception.
      console.error(e);
    }
  }

  async function mockOutdialAniList(){
    await Desktop.agentStateInfo.mockOutdialAniList()
  }

  function setNewInteraactionId(){
    setSampleIntId(newInteractionId.current.value);
  }

  return (
    <Styled styles={styles}>
      <div className="app">
        <strong>MFE Props: </strong>

        <pre>{JSON.stringify(props)}</pre>
        <hr />
        <md-tabs>
          <md-tab slot="tab">Desktop.agentStateInfo</md-tab>
          <md-tab-panel slot="panel">
            <div className="action-container">
              <h2>Monitor data output in console log</h2>
              <md-button onClick={() => getAgentInfo()}>
                Get latest Agent info
              </md-button>
              <md-button onClick={() => getClientLocale()}>
                Get current Locale
              </md-button>

              <md-button onClick={() => changeState("Idle")}>
                Change State to Idle
              </md-button>
              <md-button onClick={() => changeState("Available")}>
                Change State to Available
              </md-button>
              <md-button onClick={() => getAgentAddressBooks()}>
                Fetch Address Books
              </md-button>
              <md-button onClick={() => mockOutdialAniList()}>
                Mock Outdial Ani List
              </md-button>
            </div>
          </md-tab-panel>

          <md-tab slot="tab">Desktop.agentContact</md-tab>
          <md-tab-panel slot="panel">
            <div className="action-container">
              <h2>Desktop.agentContact sub-module</h2>
              <md-input
                htmlid="newInteractionId"
                class="input-field"
                placeholder="Enter interaction id"
                ariaLabel="Enter interaction id"
                shape="pill"
                clear=""
                value=""
                tabindex="0"
                autoFocus
                onInput = {setNewInteraactionId}
                ref={newInteractionId}
              ></md-input>
              <h3>Get Available Agents</h3>
              <p>
                Make sure to fetch latest agent info first before invoking this
                method
              </p>
              <md-button onClick={() => getBuddyAgents()}>
                Get Available Agents
              </md-button>

              <h3>Get channel specific team list</h3>
              <p>
                Make sure to fetch latest agent info first before invoking this
                method
              </p>
              <md-button onClick={() => getVTeamList()}>
                Get Team list
              </md-button>

              <h3>Accept interactions</h3>
              <span>New incoming interactions will appear here</span>

              {contacts.map((interactionId) => {
                if (acceptedContacts.indexOf(interactionId) === -1) {
                  return (
                    <md-button onClick={() => acceptInteraction(interactionId)}>
                      Accept interaction for {interactionId}
                    </md-button>
                  );
                }
                return <></>;
              })}

              <h3>End interaction</h3>
              <md-button onClick={() => endInteraction()}>
                End interaction for {sampleInteractionId}
              </md-button>

              <h3>Wrap Up interaction</h3>
              <md-button onClick={() => wrapUpInteraction()}>
                Wrap Up interaction for {sampleInteractionId}
              </md-button>

              <h3>Consult</h3>
              <md-label>
                Fetch buddy agents before initiating a consult
              </md-label>
              <md-button onClick={() => consultWithAgent()}>
                Consult with
                {buddyAgents && buddyAgents?.data.agentList.length > 0
                  ? buddyAgents?.data.agentList[0].agentId
                  : "No Agents available"}
              </md-button>

              <md-label>
                Make sure to have active conference before ending
              </md-label>
              <md-button onClick={() => endConferenceWithAgent()}>
                End Consult with
                {buddyAgents && buddyAgents?.data.agentList.length > 0
                  ? buddyAgents?.data.agentList[0].agentId
                  : "No Agents available"}
              </md-button>

              <h3>Consult Conference</h3>

              <md-button onClick={() => consultConferenceWithAgent()}>
                Consult Conference with
                {buddyAgents && buddyAgents?.data.agentList.length > 0
                  ? buddyAgents?.data.agentList[0].agentId
                  : "No Agents available"}
              </md-button>
              <md-label>
                Make sure to have active conference before ending
              </md-label>
              <md-button onClick={() => endConsultConferenceWithAgent()}>
                End Consult Conference with
                {buddyAgents && buddyAgents?.data.agentList.length > 0
                  ? buddyAgents?.data.agentList[0].agentId
                  : "No Agents available"}
              </md-button>

              <h3>Consult Transfer</h3>
              <md-button onClick={() => consultTransferToAgent()}>
                Consult Transfer to
                {buddyAgents && buddyAgents?.data.agentList.length > 0
                  ? buddyAgents?.data.agentList[0].agentId
                  : "No Agents available"}
              </md-button>

              <h3>vTeam Transfer</h3>
              <md-label>Fetch vTeam before initiating a transfer</md-label>
              <md-button onClick={() => vTeamTransfer()}>
                Consult Transfer to
                {vTeam?.data.data.vteamList[0].analyzerId}
              </md-button>
            </div>
          </md-tab-panel>

          <md-tab slot="tab">Desktop.shortcutKey</md-tab>
          <md-tab-panel slot="panel">
            <div className="“action-container”">
              <h2>Monitor data output in console log</h2>
              <md-button
                onClick={() =>
                  logger.info(Desktop.shortcutKey.DEFAULT_SHORTCUT_KEYS)
                }
              >
                Get Default Shortcut Keys
              </md-button>

              <md-button
                onClick={() => logger.info(Desktop.shortcutKey.MODIFIERS)}
              >
                Get Shortcut Keys Modifiers
              </md-button>

              <md-button
                onClick={() => logger.info(Desktop.shortcutKey.REGISTERED_KEYS)}
              >
                Get all registered Shortcut Keys
              </md-button>

              <md-button
                onClick={() =>
                  logger.info(Desktop.shortcutKey.getRegisteredKeys())
                }
              >
                Get all registered Shortcut Keys
              </md-button>
            </div>
          </md-tab-panel>

          <md-tab slot="tab">Desktop.actions</md-tab>
          <md-tab-panel slot="panel">
            <div className="action-container">
              <h2>Monitor data output in console log</h2>
              <md-button onClick={() => getToken()}>
                Get Agent Desktop auth token
              </md-button>

              <md-button onClick={() => getIdleCodes()}>
                Get idle codes
              </md-button>

              <md-button onClick={() => getwrapupCodes()}>
                Get wrap up codes
              </md-button>

              <md-button onClick={() => fireNotification()}>
                Fire notification
              </md-button>

              <md-button onClick={() => getTaskMap()}>
                Get full ist of assigned tasks including CAD variables
              </md-button>
              <md-button onClick={() => updateCADVariable()}>
                Update CAD Variables
              </md-button>
              <span>
                {assignedContacts.length > 0
                  ? assignedContacts[0].interaction.callAssociatedData &&
                    assignedContacts[0].interaction.callAssociatedData["ani"][
                      "value"
                    ] +
                      " " +
                      assignedContacts[0].interaction.callAssociatedData[
                        "customerName"
                      ]["value"]
                  : `First assigned task CAD variables will appear here.`}
              </span>
            </div>
          </md-tab-panel>

          <md-tab slot="tab">Vertical overflow tab</md-tab>
          <md-tab-panel slot="panel">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut
              ultricies lorem sem, id placerat massa rutrum eu. Sed dui neque,
              tincidunt quis sapien in, aliquam dignissim nulla. Vestibulum
              mollis at orci ac facilisis. Sed ut aliquam nunc. Suspendisse eu
              interdum odio. Sed libero dui, malesuada ac vulputate id,
              vulputate vel nisi. Proin id egestas mi. Fusce ut sem nibh.
              Vivamus aliquet accumsan feugiat. Etiam accumsan tortor quis
              ultrices tempus. Aenean porta feugiat ex. Praesent dictum mauris
              et dui posuere aliquet et non arcu. Sed eget aliquam elit. Nullam
              ornare ipsum quis feugiat tincidunt. Nullam a libero sed enim
              dictum convallis. Suspendisse egestas elit risus, at ultrices
              massa blandit eget. Vivamus dapibus bibendum nisl, eget cursus
              risus ultrices et. Quisque felis tortor, accumsan vel tempus quis,
              rutrum sed urna. Nulla quis magna et eros facilisis blandit. Nunc
              mattis urna eget diam accumsan, non vehicula est aliquet. Etiam
              vestibulum dui neque, faucibus sollicitudin nibh vestibulum vel.
              Nullam semper porta ipsum non varius. Vestibulum sollicitudin
              ipsum mauris. Praesent quis nisi sagittis, malesuada lacus semper,
              iaculis elit. Maecenas hendrerit quam ut felis pretium volutpat.
              Nulla molestie et tellus ac tincidunt. Sed sodales ultrices
              condimentum. Fusce quis rutrum dui, ut consectetur ante. Morbi
              quis sem in ipsum tempor mollis. Curabitur ac risus sed quam
              consequat faucibus quis nec neque. Nullam porttitor felis ut felis
              cursus dignissim. Curabitur tincidunt tortor et pharetra
              malesuada. Phasellus tempor ullamcorper scelerisque. Lorem ipsum
              dolor sit amet, consectetur adipiscing elit. Nulla porttitor ex
              vel egestas tristique. Aenean molestie cursus tortor at cursus.
              Sed interdum volutpat leo, sit amet placerat velit congue eu.
              Vestibulum vitae consequat ex. Ut nec venenatis augue, in porta
              massa. Curabitur quis porta felis, vel eleifend nisl. Nulla
              facilisi. Integer sagittis felis nec lacinia rutrum. Etiam a
              mauris eu nulla pulvinar auctor nec sit amet ex. Quisque turpis
              ipsum, lacinia in ex ut, tempor tempus est. Vivamus a rutrum
              velit. Donec eleifend fermentum sollicitudin. Quisque condimentum
              mauris convallis viverra tempus. Ut enim quam, pulvinar et metus
              interdum, sagittis ultricies dui. Aenean consectetur at risus eget
              ornare. Mauris pretium consequat metus a vestibulum. Nulla sit
              amet nisl eleifend, faucibus turpis at, mattis tellus. Aliquam
              vehicula orci ac nisi elementum, vitae sollicitudin odio ultrices.
              Proin in laoreet mi, vitae condimentum nibh. Nunc quis dictum
              urna, at imperdiet augue. Donec congue tempus elit quis rhoncus.
              Etiam orci quam, vestibulum egestas rutrum non, dapibus a justo.
            </p>
          </md-tab-panel>

          <md-tab slot="tab">Widget Header title update</md-tab>
          <md-tab-panel slot="panel">

          <h2>Update Dynamic widget header title</h2>
          <p>To test this functionality please add titleFor property in wrapper with unique id Example:<strong>&quot;titleFor&quot;: &quot;unique-react-id-to-update-title&quot;</strong></p>

          <pre>
            {JSON.stringify({
              "wrapper": {
                "title": "React Framework",
                "titleFor": "unique-react-id-to-update-title",
                "maximizeAreaName": "app-maximize-area"
              }
            }, undefined, 2)}
          </pre>


          <md-input
                class="input-field"
                shape="pill"
                placeholder="Enter New Title"
                clear=""
                value=""
                tabindex="0"
                autoFocus
                onInput = {(e: any)=>setTitleFor(e.target.value)}
              ></md-input>


            
            <md-button onClick={() => {
            const e = new CustomEvent("unique-react-id-to-update-title", {
              bubbles: true,
              detail: { title: titleFor }
            });
            window.dispatchEvent(e);
          }}>Update Title</md-button>
          </md-tab-panel>
        </md-tabs>
      </div>
    </Styled>
  );
};

export default App;
